language: java
sudo: true
dist: trusty
jdk: openjdk11

services:
  - postgresql
  - mongodb





addons:
  sonarcloud:
    organization: "maxiplux-github" # the key of the org you chose at step #3
    token:
      secure: $SONAR_KEY # encrypted value of your token

  hosts:
    - postgres
    #apt:
    #packages:
    #- oracle-java11-installer
before_install:
  - chmod a+x ./mvnw

before_script:
  - sleep 15
  - mongo mydb_test --eval 'db.createUser({user:"travis",pwd:"test",roles:["readWrite"]});'

deploy:
  provider: heroku
  api_key: $HEROKU_API_KEY
  app: b2bcar
  #travis encrypt HEROKU_API_KEY="d20b2f79-00a-26aa35b881ae"
script:
  #- ./mvnv verify -B
  #- ./mvnw  verify
  - ./mvnw clean verify install -B
  - sonar-scanner

#mvn sonar:sonar   -Dsonar.projectKey=maxiplux_apipostgress   -Dsonar.organization=maxiplux-github   -Dsonar.host.url=https://sonarcloud.io   -Dsonar.login=b7cc5ws83086fedd5b328a68e293a7c28d5bce1e

#sudo: required
#services:
#- docker

